algoritmo "Atividade 6"
var
      n1,n2,n3,n4,n5:Real
inicio
Escreva ("Quantas moedas de 1 real: ")
leia (n1)
Escreva ("Quantas moedas de 50 centavos: ")
leia (n2)
Escreva("Quantas moedas de 25 centavos: ")
leia (n3)
Escreva("Quantas moedas de 10 centavos: ")
leia (n4)
Escreva ("Quantas moedas de 5 centavos: ")
leia(n5)
n1<-n1+n2*0.50+n3*0.25+n4*0.1+n5*0.05
Escreva ("no Total tem ",n1,"reais")
fimalgoritmo
