algoritmo "semnome"

var
   a,b,c,d,f:inteiro
   m:real
inicio
      Escreva("Escreva um valor: ")
      leia(a)
      Escreva("Escreva um valor: ")
      leia(b)
      Escreva("Escreva um valor: ")
      leia(c)
      Escreva("Escreva um valor: ")
      leia(d)
      Escreva("Escreva um valor: ")
      leia(f)
      m<-(a+b+c+d+f)/5
      escreva("A media de ",a,", ",b,", ",c,", ",d," e ",f," é ",m)
      
fimalgoritmo
