algoritmo "Atividade 7"
// Data : 11/04/2017
var
   A,B: inteiro
   C: caracter
inicio

      Escreva("Escreva um numero: ")
      leia(A)
      Escreva("Escreva um numero: ")
      leia(B)
      Se A mod 2 = 0 entao
         Escreva(A," é multiplo de 2 ")
      Senao
         Escreva(A," não é multiplo de 2 ")
      FimSe
      Se B mod 2 = 0 entao
        Escreva(B," é multiplo de 2")
      Senao
         Escreva(B," não é multiplo de 2")
      FimSe

fimalgoritmo
